## 矩阵的翻转操作和轴的转换

In [1]:
import numpy as np

image = [[0, 0, 0, 255],
        [0, 0, 255, 0],
        [0, 255, 0, 0],
        [255, 0, 0, 0],
        [0, 255, 0, 0],
        [0, 0, 255, 0],
        [0, 0, 0, 255]]
image = np.array(image)
print(image)

[[  0   0   0 255]
 [  0   0 255   0]
 [  0 255   0   0]
 [255   0   0   0]
 [  0 255   0   0]
 [  0   0 255   0]
 [  0   0   0 255]]


In [3]:
np.transpose(image)

array([[  0,   0,   0, 255,   0,   0,   0],
       [  0,   0, 255,   0, 255,   0,   0],
       [  0, 255,   0,   0,   0, 255,   0],
       [255,   0,   0,   0,   0,   0, 255]])

`np.transpose`作为函数，可以通过参数实现更复杂的功能：

In [5]:
a = np.arange(24).reshape(2, 3, 4)
b = np.transpose(a,[1, 0, 2])
print(a.shape)
print(b.shape)

(2, 3, 4)
(3, 2, 4)


`np.swapaxes`将数组数组中指定的两个轴进行交换：

In [6]:
a = np.arange(24).reshape(2, 3, 4)
np.swapaxes(a, 0, 2).shape

(4, 3, 2)

也可以完成转置：

In [7]:
a = np.arange(15).reshape(3, 5)
np.swapaxes(a, 0, 1)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

`np.rollaxis`可以将某个轴放到指定位置：

In [8]:
a = np.arange(720).reshape(2, 3, 4, 5, 6)
np.rollaxis(a, 2, 4).shape #把2轴放到4轴前

(2, 3, 5, 4, 6)

In [10]:
np.rollaxis(a, 1).shape

(3, 2, 4, 5, 6)

第三个参数，默认取值为0：

In [ ]:
np.rollaxis(a, 2).shape 

#### 总结
1. `.T` 得到矩阵的转置

矩阵轴的转换：<br>

2. `np.transpose()` 

3. `np.swapaxes()`

4. `np.rollaxis()`

5. `np.flip()`实现图像的翻转

#### 思考：
编写一个函数，接受两个矩阵作为输入，<br>返回两个矩阵的转置矩阵的乘积
<br>(`np.dot`方法可以实现矩阵乘法)。