## 元素的搜索

In [3]:
import numpy as np
a = np.array([[3, 7, 3, 1], [9, 7, 8, 7]])
print(a)
print(np.argmax(a)) 
print(np.argmin(a)) 

print(np.where(a > 3))

[[3 7 3 1]
 [9 7 8 7]]
4
3
(array([0, 1, 1, 1, 1]), array([1, 0, 1, 2, 3]))


`np.argmax`和`np.argmin`可以获取最大值和最小值位置下标。
<br>那`np.where`如何理解？

In [4]:
aa = np.arange(10)
print(aa)
np.where(aa > 5,1,-1)

[0 1 2 3 4 5 6 7 8 9]


array([-1, -1, -1, -1, -1, -1,  1,  1,  1,  1])

In [5]:
np.where(aa, 1, -1)

array([-1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

`np.where(condition, x, y)` 满足条件(condition)，<br>输出x，不满足输出y。

In [7]:
np.where([[True,False], [False,True]], 
         [[1,2], [3,4]],
         [[9,8], [7,6]])

array([[1, 8],
       [7, 4]])

类似的问题可以再看个例子：

In [8]:
a = 10
np.where([[a > 5,a < 5], [a == 10,a == 7]],
         [["chosen","not chosen"], ["chosen","not chosen"]],
         [["not chosen","chosen"], ["not chosen","chosen"]])

array([['chosen', 'chosen'],
       ['chosen', 'chosen']], dtype='<U10')

`np.where(condition)`<br>
只有条件 (condition)，没有x和y，则输出满足条件 (即非0) 元素的坐标：

In [9]:
a = np.array([2,4,6,8,10])
np.where(a > 5)

(array([2, 3, 4]),)

In [10]:
a[np.where(a > 5)]  

array([ 6,  8, 10])

In [11]:
a = np.array([[3, 7, 3, 1], [9, 7, 8, 7]])
print(np.where(a > 3))

(array([0, 1, 1, 1, 1]), array([1, 0, 1, 2, 3]))


这里的坐标以tuple的形式给出，tuple中数组个数与原数组维数相同。

#### 总结
1. `np.where(condition, x, y)`：<br>根据condition的真假选择x或y中的元素。

2. `np.where(condition)`：<br>返回满足condition条件的元素的索引。

3. `x[np.where(condition)] = value`：<br>将满足condition条件的元素修改为指定的value值。

#### 思考1：
使用`np.where`来实现，将一个数组中<br>小于等于阈值5的元素设置为0，大于阈值的元素放大十倍。

In [13]:
a = np.arange(10)
print(a)
np.where(a <= 5, 0, a*10)

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  0,  0,  0,  0,  0, 60, 70, 80, 90])

#### 思考2：
现有如下语句：
```Python
import numpy as np
np.where([[1, 1], [1, 0]])
```
请对该语句的返回值进行解释。

此时元素为1的位置坐标，元组中第一个数组为所有为1的元素的0轴坐标，第二个数组为所有为1元素的1轴坐标。所以当前其实是定位到3个位置：00，01，10。所以这里有几个维度，元组中就应该有几个数组。

In [14]:
import numpy as np
np.where([[1, 1], [1, 0]])

(array([0, 0, 1]), array([0, 1, 0]))

## IO文件操作

In [15]:
import numpy as np

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.savetxt('data.txt', data)

In [16]:
loadtxt = np.loadtxt('data.txt')
print(loadtxt)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
np.save('data.npy', data)
loaded_arr = np.load('data.npy')
print("加载的数组：", loaded_arr)

#### 总结：
1. `save()`和`load()`
    <br>以npy文件格式的存储和获取数组数据。
2. `savetxt()`和`loadtxt()` 
    <br>以简单文本文件格式存储和获取数组数据。